### ISSUE TITLE
Rows width Issue

### ISSUE THREAD

**Issue by cliffgr** [vkvashistha/multiviewrecyclerview#1]
The items of the recyclerView are marked as match_parent but this seems is not working. I just tested adding color to the background in order to see the item container

![image](https://user-images.githubusercontent.com/4539769/131800730-7c6c0cdf-56cc-41b7-86ee-6dbb4469bb1b.png)

**Comment by manishkummar21** [comment]
@cliffgr Please change this line16 in MultiViewViewHolderProvider
            viewHolderTypes[viewType]!!.getConstructor(View::class.java).newInstance(LayoutInflater.from(parent.context).inflate(viewType, parent,false))

**Comment by vkvashistha** [comment]
Issue resolved with solution suggested by @manishkummar21 . Thanks
